% PURPOSE: build the default Classic ERPLAB working-memory structure
%
% FORMAT:
%
% s = erplab_default_memory_struct(mshock)

function s = erplab_default_memory_struct(mshock)

if nargin < 1 || isempty(mshock)
    mshock = 0;
end

erplab_default_values

s = struct('erplabrel', erplabrel, ...
    'erplabver', erplabver, ...
    'ColorB', ColorB, ...
    'ColorF', ColorF, ...
    'fontsizeGUI', fontsizeGUI, ...
    'fontunitsGUI', fontunitsGUI, ...
    'mshock', mshock, ...
    'errorColorF', errorColorF, ...
    'errorColorB', errorColorB);

end
